apiVersion: v1
kind: Template
metadata:
  name: datastax-node-template
  annotations:
    description: "Create a node of Datastax"
    tags: "database,nosql"
objects:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: datastax-data-node-${NUMBER_NODE}
    annotations:
      volume.beta.kubernetes.io/storage-class: glusterfs-storage
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 2Gi

- apiVersion: v1
  kind: Pod
  metadata:
    name: datastax-node-${NUMBER_NODE}
      labels:
        cluster: datastax-node-${NUMBER_NODE}
  spec:
    containers:
    - env:
      - name: DS_LICENSE
        value: "accept"
      - name: SEEDS
        value: ${SEEDS}
      - name: CLUSTER_NAME
        value: ${CLUSTER_NAME}
      - name: NUM_TOKENS
        value: "256"
      - name: START_RPC
        value: "true"
      image: datastax/dse-server
      name: node-${NUMBER_NODE}
      volumeMounts:
      - name: datastax-data-volume-${NUMBER_NODE}
        mountPath: /var/lib/cassandra
        readOnly: false
      ports:
      - containerPort: 4040
        protocol: TCP
      - containerPort: 5598
        protocol: TCP
      - containerPort: 5599
        protocol: TCP
      - containerPort: 7000
        protocol: TCP
      - containerPort: 7001
        protocol: TCP
      - containerPort: 7077
        protocol: TCP
      - containerPort: 7080
        protocol: TCP
      - containerPort: 7081
        protocol: TCP
      - containerPort: 7199
        protocol: TCP
      - containerPort: 8090
        protocol: TCP
      - containerPort: 8182
        protocol: TCP
      - containerPort: 8609
        protocol: TCP
      - containerPort: 8983
        protocol: TCP
      - containerPort: 8984
        protocol: TCP
      - containerPort: 9042
        protocol: TCP
      - containerPort: 9103
        protocol: TCP
      - containerPort: 9160
        protocol: TCP
      - containerPort: 9999
        protocol: TCP
      - containerPort: 10000
        protocol: TCP
      - containerPort: 18080
        protocol: TCP
    volumes:
    - name: datastax-data-volume-${NUMBER_NODE}
      persistentVolumeClaim:
        claimName: datastax-data-node-${NUMBER_NODE}

- apiVersion: v1
  kind: Service
  metadata:
    name: datastax-service-${NUMBER_NODE}
      labels:
        cluster: datastax-node-${NUMBER_NODE}
  spec:
    ports:
      - name: 4040-tcp
        port: 4040
        targetPort: 4040
        protocol: TCP
      - name: 5598-tcp
        port: 5598
        targetPort: 5598
        protocol: TCP
      - name: 5599-tcp
        port: 5599
        protocol: TCP
        targetPort: 5599
      - name: 7000-tcp
        port: 7000
        protocol: TCP
        targetPort: 7000
      - name: 7001-tcp
        port: 7001
        protocol: TCP
        targetPort: 7001
      - name: 7077-tcp
        port: 7077
        protocol: TCP
        targetPort: 7077
      - name: 7080-tcp
        port: 7080
        protocol: TCP
        targetPort: 7080
      - name: 7081-tcp
        port: 7081
        protocol: TCP
        targetPort: 7081
      - name: 7199-tcp
        port: 7199
        protocol: TCP
        targetPort: 7199
      - name: 8090-tcp
        port: 8090
        protocol: TCP
        targetPort: 8090
      - name: 8182-tcp
        port: 8182
        protocol: TCP
        targetPort: 8182
      - name: 8609-tcp
        port: 8609
        protocol: TCP
        targetPort: 8609
      - name: 8683-tcp
        port: 8983
        protocol: TCP
        targetPort: 8983
      - name: 8984-tcp
        port: 8984
        protocol: TCP
        targetPort: 8984
      - name: 9042-tcp
        port: 9042
        protocol: TCP
        targetPort: 9042
      - name: 9103-tcp
        port: 9103
        protocol: TCP
        targetPort: 9103
      - name: 9160-tcp
        port: 9160
        protocol: TCP
        targetPort: 9160
      - name: 9999-tcp
        port: 9999
        protocol: TCP
        targetPort: 9999
      - name: 10000-tcp
        port: 10000
        protocol: TCP
        targetPort: 10000
      - name: 18080-tcp
        port: 18080
        protocol: TCP
        targetPort: 18080
    selector:
      cluster: datastax-node-${NUMBER_NODE}

            
parameters:
  - name: NUMBER_NODE
    description: "Número de nodo que se añade al cluster"
    displayName: Number node 
    requiered: true
  - name: CLUSTER_NAME
    description: "Nombre del cluster al que queremos agregar el nodo"
    displayName: Nobre del cluster
    requiered: true
  - name: SEEDS
    description: "Lista de nodos semilla del cluster"
    displayName: Semillas
    requiered: false
